version: '3.1'

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_SUPERUSER_USER}"
      POSTGRES_PASSWORD: "${DATABASE_SUPERUSER_PASSWORD}"